# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20160831_1700'),
        ('tenant', '0002_tenant_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_address',
            field=models.ForeignKey(default='1c72f896-8beb-40ae-8a92-385dba0ed418', on_delete=django.db.models.deletion.CASCADE, to='contact.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_email',
            field=models.ForeignKey(default='1c72f896-8beb-40ae-8a92-385dba0ed410', on_delete=django.db.models.deletion.CASCADE, related_name='billing_emails', to='contact.Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_phone_number',
            field=models.ForeignKey(default='1c72f896-8beb-40ae-8a92-385dba0ed411', on_delete=django.db.models.deletion.CASCADE, to='contact.PhoneNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='implementation_contact',
            field=models.CharField(default=1, max_length=100, verbose_name='Implementation Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='implementation_contact_initial',
            field=models.CharField(default=1, max_length=100, verbose_name='Implementation Contact (Initial)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='implementation_email',
            field=models.ForeignKey(default='1c72f896-8beb-40ae-8a92-385dba0ed412', on_delete=django.db.models.deletion.CASCADE, related_name='implementation_emails', to='contact.Email'),
            preserve_default=False,
        ),
    ]
