# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20160913_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_emails', to='contact.Address'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='billing_phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_phone_numbers', to='contact.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='implementation_contact',
            field=models.ForeignKey(help_text='Then Tenant Admin Person', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='implementation_contact_initial',
            field=models.CharField(help_text='String name of the initial User that signs up that will be the Tenant Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='implementation_email',
            field=models.ForeignKey(help_text='Email that will be used to send to the initual User that signs up', on_delete=django.db.models.deletion.CASCADE, related_name='implementation_emails', to='contact.Email'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='When in test mode all e-mail and other notifications will be sent to test addresses only'),
        ),
    ]
