# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_auto_20160914_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='scid',
            field=models.UUIDField(help_text='id of SC primary key record of the subscriber. Will be null on initial BS create', null=True),
        ),
    ]
