# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_tenant_scid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='scid',
            field=models.CharField(blank=True, help_text='id of SC primary key record of the subscriber. Will be null on initial BS create', max_length=25, null=True),
        ),
    ]
