# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_auto_20161007_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='dt_start',
            new_name='dtd_start',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(help_text='Full customer company name', max_length=100, unique=True),
        ),
    ]
