# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_auto_20160714_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefilter',
            name='key',
            field=models.CharField(default='admin.placeholder.ticket_priority', help_text='To use for i18n UI key, and also for mapping component used for this filter select', max_length=100),
            preserve_default=False,
        ),
    ]
