# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0006_profilefilter_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefilter',
            name='key',
            field=models.CharField(help_text='To use for i18n UI key, and also for mapping component based on selected filter', max_length=100),
        ),
    ]
