# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0013_auto_20160822_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='assignee',
        ),
    ]
