# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DominoRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('selection', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('manage_role_names', models.TextField(blank=True, null=True)),
                ('tsg_start_point', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
