# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tperson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DominoPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('first_name', models.TextField(blank=True, null=True)),
                ('middle_initial', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('role', models.TextField()),
                ('status', models.TextField()),
                ('locations', models.TextField(blank=True, null=True)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('email_address', models.TextField(blank=True, null=True)),
                ('sms_address', models.TextField(blank=True, null=True)),
                ('auth_amount', models.TextField(blank=True, null=True)),
                ('next_approver', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DominoRole',
        ),
    ]
