# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tperson', '0002_auto_20160317_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominoperson',
            name='name',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
