# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tperson', '0003_dominoperson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominoperson',
            name='middle_initial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
