# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationfilter',
            name='context',
            field=models.CharField(blank=True, default='ticket.ticket', help_text="The namespace of the model to look the field up on. ex: 'app_name.model_name'", max_length=100),
        ),
    ]
