# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('automation', '0003_auto_20160713_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='order',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automation',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant'),
        ),
    ]
