# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 16:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_auto_20160722_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationFilterType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('type', models.CharField(default='automation', help_text='could be different for the model being filtered. i.e. automation, notification, etc...', max_length=100, null=True)),
                ('key', models.CharField(blank=True, help_text='To use for i18n UI key, and also for mapping component based on selected filter', max_length=100)),
                ('key_is_i18n', models.BooleanField(default=True, help_text="is the 'key' field i18n'able")),
                ('context', models.CharField(blank=True, default='ticket.ticket', help_text="The namespace of the model to look the field up on. ex: 'app_name.model_name'", max_length=100)),
                ('field', models.CharField(help_text="Model field to look up from the Model class specified in the 'context'", max_length=100)),
                ('lookups', django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text="if used, provide extra lookup information beyond the 'field'this should be a string array", null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
