# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_auto_20160726_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefilter',
            name='context',
        ),
        migrations.RemoveField(
            model_name='profilefilter',
            name='field',
        ),
        migrations.RemoveField(
            model_name='profilefilter',
            name='key',
        ),
        migrations.RemoveField(
            model_name='profilefilter',
            name='key_is_i18n',
        ),
        migrations.AddField(
            model_name='profilefilter',
            name='source',
            field=models.ForeignKey(default='52d4fa9f-73d5-4dec-8431-96ada3aee2dd', help_text='Use to get info on what type of filter, if this is a dynamic filter, usethe lookup field', on_delete=django.db.models.deletion.CASCADE, to='automation.AvailableFilter'),
            preserve_default=False,
        ),
    ]
