# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_auto_20160727_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablefilter',
            name='key_is_i18n',
        ),
    ]
