# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_remove_automation_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automation',
            options={'ordering': ['description']},
        ),
        migrations.RemoveField(
            model_name='automation',
            name='order',
        ),
    ]
