# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 23:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_auto_20160920_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.Automation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationActionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('key', models.CharField(choices=[('automation.actions.email', 'automation.actions.email'), ('automation.actions.text', 'automation.actions.text'), ('automation.actions.ticket_assignee', 'automation.actions.ticket_assignee'), ('automation.actions.ticket_attachment', 'automation.actions.ticket_attachment'), ('automation.actions.ticket_cc', 'automation.actions.ticket_cc'), ('automation.actions.ticket_priority', 'automation.actions.ticket_priority'), ('automation.actions.ticket_request', 'automation.actions.ticket_request'), ('automation.actions.ticket_status', 'automation.actions.ticket_status')], max_length=100, unique=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='automationaction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.AutomationActionType'),
        ),
    ]
