version: '2'

services:
  postgres:  
    build:
      context: .
      dockerfile: Dockerfile-psql
    env_file:
      - ./bsrs-django/env/app.${APP_ENV}.env
    ports:
      - "5432:5432"
    networks:
      - bsrs_default

  django:  
    build: 
      context: ./bsrs-django
      dockerfile: ./docker/dev/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: bigsky.settings.ci
      DATABASE_HOST: postgres
    volumes:
      - .:/www/src/bsrs-django
    expose:
      - "8000"
    links: 
      - postgres
    networks:
      - bsrs_default

  builder:
    build:
      context: ./bsrs-django
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ./target:/wheelhouse
    volumes_from:
      - cache
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build", "."]

  # agent:
  #   image: bsrs/ansible
  #   volumes:
  #     - ./bsrs-django/docker/ansible/probe.yml:/ansible/site.yml
  #   links:
  #     - postgres 
  #   environment:
  #     PROBE_HOST: "postgres"
  #     PROBE_PORT: "5432"

  cache:
    build: 
      context: ./bsrs-django
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - /tmp/cache:/cache
      - /build
    entrypoint: "true"

networks:
  bsrs_default:
    driver: bridge

  # nginx:
  #   build: ./builds
  #   volumes:
  #     - /www/static
  #   volumes_from:
  #     - uwsgi
  #   links:
  #     - uwisgi
  #   ports:
  #     - "5432"

  # ember:  
  #   build: 
  #     context: ./bsrs-ember
  #     dockerfile: Dockerfile
  #   environment:
  #     - EMBER_ENV=development
  #   ports:
  #     - "4200:4200"
  #     - "49152:49152"

  # uwsgi:
  #   build: .
  #   links:
  #     - postgres
  #   command: ./uwsgi.sh
  #   volumes:
  #     - /static
  #     - /data/media:/media
  # nginx: sudo service nginx status
  # postgres: systemctl command postgres.rst, db deploy, username and password, 
  #
  #ci:
    # image: jenkins:2.0
    # ports:
    #  - "8080:8080"
    #  - "50000:50000"
    # links:
    # - django
