# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='person',
            field=models.ForeignKey(default='10915de0-5f78-4704-9b5b-8beb2974900b', help_text='The Person who saves the search.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
