# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20160125_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'login_grace': {'required': True, 'type': 'int', 'value': 1}})),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
