# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 23:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20151217_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsetting',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customsetting',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='mainsetting',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mainsetting',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='customsetting',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='mainsetting',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
