# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_auto_20160106_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSetting',
        ),
        migrations.DeleteModel(
            name='MainSetting',
        ),
    ]
