# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 18:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
