# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_auto_20160127_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'ordering': ('-modified',), 'verbose_name_plural': 'Saved searches'},
        ),
    ]
