# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('generic', '0006_delete_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='ticket',
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='object_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
