# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0007_auto_20160226_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
