from .base import *


TEMPLATE_DEBUG = DEBUG = False

### TICKETS
TICKET_FILTERING_ON = True

# SSL_ENABLED = True
# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SECURE = True
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_AGE = 5400
# SESSION_SAVE_EVERY_REQUEST = True

# REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = ('rest_framework.renderers.JSONRenderer', )
