# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='address_1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='address_2',
            new_name='address2',
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
