# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20161230_0008'),
        ('provider', '0002_auto_20170111_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='category',
        ),
        migrations.AddField(
            model_name='provider',
            name='category',
            field=models.ManyToManyField(related_name='providers', to='category.Category'),
        ),
    ]
