# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20170117_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='category',
            new_name='categories',
        ),
    ]
