# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20170117_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='country_code',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='region_name',
            new_name='state',
        ),
    ]
