# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketpriority',
            options={'verbose_name_plural': 'Ticket priorities'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'verbose_name_plural': 'Ticket statuses'},
        ),
    ]
