# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requester',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
