# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20160713_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketactivity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='person',
            field=models.ForeignKey(help_text='Person who did the TicketActivity. NULL would be a system recoreded Activity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketactivitytype',
            name='name',
            field=models.CharField(choices=[('create', 'create'), ('assignee', 'assignee'), ('cc_add', 'cc_add'), ('cc_remove', 'cc_remove'), ('status', 'status'), ('priority', 'priority'), ('categories', 'categories'), ('comment', 'comment'), ('attachment_add', 'attachment_add'), ('send_email', 'send_email'), ('send_sms', 'send_sms')], max_length=100, unique=True),
        ),
    ]
