# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-15 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20160217_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requester',
            field=models.CharField(blank=True, help_text='The User or string inputted by User', max_length=150, null=True),
        ),
    ]
