# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 21:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20160106_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketactivity',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
