# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20161122_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketactivitytype',
            name='name',
            field=models.CharField(choices=[('create', 'create'), ('assignee', 'assignee'), ('cc_add', 'cc_add'), ('cc_remove', 'cc_remove'), ('status', 'status'), ('priority', 'priority'), ('categories', 'categories'), ('comment', 'comment'), ('attachment_add', 'attachment_add'), ('send_email', 'send_email'), ('send_sms', 'send_sms'), ('request', 'request')], max_length=100, unique=True),
        ),
    ]
