# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20161123_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketactivity',
            name='deleted',
            field=models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
