# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='metadata',
            new_name='dt_path',
        ),
    ]
