# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_auto_20161004_1852'),
        ('ticket', '0005_auto_20161128_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketactivity',
            name='automation',
            field=models.ForeignKey(help_text='Automation who did the TicketActivity. NULL would be a Person generated Activity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_activities', to='automation.Automation'),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='person',
            field=models.ForeignKey(help_text='Person who did the TicketActivity. NULL would be an Automation generated Activity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
