# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20160422_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(blank=True, default=ticket.models.Ticket.no_ticket_models, unique=True),
        ),
    ]
