# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20161205_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstatus',
            name='name',
            field=models.CharField(choices=[('ticket.status.cancelled', 'ticket.status.cancelled'), ('ticket.status.complete', 'ticket.status.complete'), ('ticket.status.deferred', 'ticket.status.deferred'), ('ticket.status.denied', 'ticket.status.denied'), ('ticket.status.draft', 'ticket.status.draft'), ('ticket.status.in_progress', 'ticket.status.in_progress'), ('ticket.status.new', 'ticket.status.new'), ('ticket.status.pending', 'ticket.status.pending'), ('ticket.status.solved', 'ticket.status.solved'), ('ticket.status.unsatisfactory', 'ticket.status.unsatisfactory')], default='ticket.status.new', max_length=100),
        ),
    ]
