# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20161219_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='dt_path',
        ),
    ]
