# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0007_auto_20160428_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(help_text='The logged in Person that created the Ticket. If NULL, it was system created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
