# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20160502_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='legacy_ref_number',
            field=models.CharField(blank=True, help_text='Legacy ticket number from Domino', max_length=254, null=True),
        ),
    ]
