# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_legacy_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
