# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 23:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20160503_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dt_path',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
    ]
