# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20160505_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('number',)},
        ),
    ]
