# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_locationlevel_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='scid',
            field=models.IntegerField(help_text='id of SC primary key record of the location. Will be null on initial BS create', null=True, unique=True),
        ),
    ]
