# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_scid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlevel',
            name='name',
            field=models.CharField(help_text='unique by tenant', max_length=100),
        ),
    ]
