# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20161229_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationlevel',
            name='tenant',
            field=models.ForeignKey(default='037530c4-ce6c-4724-9cfd-37a16e787001', on_delete=django.db.models.deletion.CASCADE, related_name='location_levels', to='tenant.Tenant'),
            preserve_default=False,
        ),
    ]
