# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20160628_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='accept_assign',
        ),
        migrations.RemoveField(
            model_name='person',
            name='accept_notify',
        ),
        migrations.RemoveField(
            model_name='role',
            name='accept_assign',
        ),
        migrations.RemoveField(
            model_name='role',
            name='accept_notify',
        ),
    ]
