# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 01:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20160112_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
