# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20151230_1409'),
        ('person', '0003_auto_20160106_0904'),
    ]

    operations = [
    ]
