# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20160725_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='process_assign',
            field=models.BooleanField(default=True, help_text='If True, run the Ticket Assignment Profiles after a Ticket is create, but if False, assign to the Person who created the Ticket'),
        ),
    ]
