# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20160627_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accept_assign',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='accept_notify',
            field=models.NullBooleanField(),
        ),
    ]
