# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20160802_1753'),
        ('person', '0004_role_process_assign'),
    ]

    operations = [
    ]
