# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20160627_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password_one_time',
            field=models.BooleanField(default=False),
        ),
    ]
