# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_role_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('fullname',), 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='personstatus',
            options={'verbose_name_plural': 'Person statuses'},
        ),
    ]
