# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_merge_20160802_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('fullname',), 'verbose_name_plural': 'People'},
        ),
    ]
