# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20160627_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='dashboard_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
