# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20161007_1626'),
        ('person', '0006_auto_20160920_1818'),
    ]

    operations = [
    ]
