# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-02 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20160307_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
