# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20160628_2247'),
        ('person', '0006_auto_20161007_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.Attachment'),
        ),
    ]
