# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_person_photo'),
        ('person', '0007_merge_20161025_1818'),
    ]

    operations = [
    ]
