# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20160413_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='category.Category'),
        ),
    ]
