# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20161206_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Will be set to the Group Name', max_length=75),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(default='037530c4-ce6c-4724-9cfd-37a16e787001', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenant.Tenant'),
            preserve_default=False,
        ),
    ]
