# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20161229_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='unique by tenant', max_length=75),
        ),
    ]
