# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_remove_personstatus_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='default_auth_amount',
            new_name='auth_amount',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='default_auth_currency',
            new_name='auth_currency',
        ),
    ]
