# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 00:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_auto_20160516_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
