# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_person_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='role',
            name='settings',
        ),
    ]
