# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_auto_20160519_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='auth_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
