# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_auto_20160614_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='dt_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtd.TreeData'),
        ),
    ]
