# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_auto_20160615_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='person.Tenant'),
        ),
    ]
