# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('person', '0022_auto_20160615_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='auth_currency',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='settings',
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_code',
            field=models.CharField(default=1, help_text='Short code used to identify customer', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(default=1, help_text='Full customer company name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='dashboard_text',
            field=models.TextField(blank=True, default='Welcome', help_text='Converts to HTML for display on Welcome page. Role inherits this field'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_currency',
            field=models.ForeignKey(help_text='key to default currency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='accounting.Currency'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='test_mode',
            field=models.BooleanField(default=True, help_text='When in test mode all e-mail and other notifications will be sent to test addresses only'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='dt_start',
            field=models.ForeignKey(help_text='key to starting decision tree record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='dtd.TreeData'),
        ),
    ]
