# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_auto_20160622_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='dt_start',
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenant.Tenant'),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
