# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 19:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('context', models.CharField(blank=True, default='ticket.Ticket', help_text="The namespace of the model to look the field up on. ex: 'app_name.model_name'", max_length=100)),
                ('field', models.CharField(help_text="Model field to look up from the Model class specified in the 'context'", max_length=100)),
                ('criteria', django.contrib.postgres.fields.jsonb.JSONField(help_text='Must be a list. Criteria to match on.')),
                ('object_id', models.UUIDField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
