# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_code', models.TextField(blank=True, null=True)),
                ('cost_amount', models.TextField(blank=True, null=True)),
                ('trade_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_code', models.TextField(blank=True, null=True)),
                ('cost_amount', models.TextField(blank=True, null=True)),
                ('type_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_code', models.TextField(blank=True, null=True)),
                ('cost_amount', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
