# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 22:47
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models

import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, editable=False, help_text='This field cannot be set directly.  It is either set from a system setting, or defaulted from the Parent Category.', max_length=100, null=True)),
                ('subcategory_label', models.CharField(blank=True, max_length=100)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('cost_code', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, default=0, help_text='A count of how many parent categories that this Category has.')),
                ('cost_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Currency')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('level',),
            },
        ),
        migrations.CreateModel(
            name='CategoryStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Category statuses',
            },
            bases=(utils.models.ToDictNameMixin, models.Model),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.CategoryStatus'),
        ),
    ]
