# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20161230_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sc_category_name',
            field=models.CharField(blank=True, help_text='Mapping to SC Category name', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='cost_amount',
            field=models.DecimalField(decimal_places=4, help_text='aka (NTE) not to exceed amount', max_digits=15, null=True),
        ),
    ]
