# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20160120_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('level',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorystatus',
            options={'verbose_name_plural': 'Category statuses'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
