# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20170117_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('sc_name', models.CharField(help_text='SC trade name', max_length=100, unique=True)),
                ('key', models.CharField(help_text="i18n key of string name for UI. English version will be the prettified 'SC trade name'.", max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
