# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_auto_20170118_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='cost_estimate',
            field=models.DecimalField(decimal_places=4, help_text='SC field: Nte', max_digits=9),
        ),
    ]
