# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_auto_20170120_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='approved_amount',
            field=models.DecimalField(decimal_places=4, help_text='May be the same as cost_estimate', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='cost_estimate',
            field=models.DecimalField(decimal_places=4, help_text='SC field: Nte - will change based on the amount the Provider estimates for the work', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='cost_estimate_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Currency'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='instructions',
            field=models.TextField(blank=True, help_text='SC field: Description, Required for SC API', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='location',
            field=models.ForeignKey(help_text='SC field: ContractInfo/LocationId, Required for SC API', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='location.Location'),
        ),
    ]
