# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 22:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_ticket_dt_path'),
        ('work_order', '0004_auto_20170123_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='ticket',
            field=models.ForeignKey(help_text='nullable because WorkOrders can exist without a Ticket', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='ticket.Ticket'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
