# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_auto_20170123_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='date the work order is created, and gets updated if approval amount changes', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='approver',
            field=models.ForeignKey(help_text='Person who creates the work order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='same as SC work_date, left blank until completed', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='original ETA', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='SC field: work order number', max_length=128, null=True),
        ),
    ]
