# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0006_auto_20170124_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='gl_code',
            field=models.CharField(blank=True, help_text='an inherited value from the category', max_length=100, null=True),
        ),
    ]
