# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_workorder_scid'),
        ('work_order', '0007_workorder_gl_code'),
    ]

    operations = [
    ]
