# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0007_merge_20170201_1818'),
        ('work_order', '0008_merge_20170201_0135'),
    ]

    operations = [
    ]
