# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0009_merge_20170201_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='requester',
            field=models.CharField(blank=True, help_text='The User or string inputted by User', max_length=150, null=True),
        ),
    ]
