# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 23:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.db.models.deletion
import translation.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('locale', models.SlugField(help_text='Example values: en, en-US, en-x-Sephora')),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="Human readable name in forms. i.e. 'English'", max_length=50)),
                ('native_name', models.CharField(blank=True, max_length=50, null=True)),
                ('presentation_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rtl', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('values', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={})),
                ('context', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={})),
                ('csv', models.FileField(blank=True, null=True, upload_to=translation.models.translation_file)),
                ('locale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translation.Locale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
