# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='locale',
            field=models.CharField(help_text='Example values: en, en-US, en-x-Sephora', max_length=50, unique=True),
        ),
    ]
