# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DominoTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.TextField()),
                ('location_number', models.TextField()),
                ('wo_number', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('priority', models.TextField()),
                ('type', models.TextField()),
                ('trade', models.TextField(blank=True, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('requester', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
