# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominoticket',
            name='location_number',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dominoticket',
            name='ref_number',
            field=models.TextField(db_index=True),
        ),
    ]
