# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('address',)},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address2',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
    ]
