# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20160729_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='classification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
