# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20160729_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='country_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
