# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20160730_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
