# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20160831_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='address',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='email',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
