# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_profile_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order',
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
