# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('key', models.CharField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('note_type', models.CharField(blank=True, choices=[('admin.dtd.note_type.success', 'admin.dtd.note_type.success'), ('admin.dtd.note_type.info', 'admin.dtd.note_type.info'), ('admin.dtd.note_type.warning', 'admin.dtd.note_type.warning'), ('admin.dtd.note_type.danger', 'admin.dtd.note_type.danger')], default='admin.dtd.note_type.success', max_length=1000)),
                ('prompt', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_type', models.CharField(blank=True, choices=[('admin.dtd.link_type.buttons', 'admin.dtd.link_type.buttons'), ('admin.dtd.link_type.links', 'admin.dtd.link_type.links')], default='admin.dtd.link_type.buttons', max_length=1000)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='TreeField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('label', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('admin.dtd.label.field.text', 'admin.dtd.label.field.text'), ('admin.dtd.label.field.number', 'admin.dtd.label.field.number'), ('admin.dtd.label.field.textarea', 'admin.dtd.label.field.textarea'), ('admin.dtd.label.field.select', 'admin.dtd.label.field.select'), ('admin.dtd.label.field.checkbox', 'admin.dtd.label.field.checkbox'), ('admin.dtd.label.field.file', 'admin.dtd.label.field.file'), ('admin.dtd.label.field.asset_select', 'admin.dtd.label.field.asset_select'), ('admin.dtd.label.field.check_in', 'admin.dtd.label.field.check_in'), ('admin.dtd.label.field.check_out', 'admin.dtd.label.field.check_out')], default='admin.dtd.label.field.text', max_length=100)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('text', models.CharField(max_length=1000)),
                ('action_button', models.BooleanField(default=False)),
                ('is_header', models.BooleanField(default=False)),
                ('request', models.CharField(blank=True, max_length=1000, null=True)),
                ('categories', models.ManyToManyField(related_name='links', to='category.Category')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtd.TreeData')),
                ('dtd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dtd.TreeData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreeOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('text', models.CharField(max_length=1000)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dtd.TreeField')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
