# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic', '0006_delete_setting'),
        ('category', '0005_auto_20160217_1642'),
        ('ticket', '0002_auto_20160217_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('key', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('note_type', models.CharField(blank=True, choices=[('admin.dtd.note_type.success', 'admin.dtd.note_type.success'), ('admin.dtd.note_type.info', 'admin.dtd.note_type.info'), ('admin.dtd.note_type.warning', 'admin.dtd.note_type.warning'), ('admin.dtd.note_type.danger', 'admin.dtd.note_type.danger')], default='admin.dtd.note_type.success', max_length=1000)),
                ('prompt', models.CharField(max_length=1000)),
                ('link_type', models.CharField(blank=True, choices=[('admin.dtd.link_type.buttons', 'admin.dtd.link_type.buttons'), ('admin.dtd.link_type.links', 'admin.dtd.link_type.links')], default='admin.dtd.link_type.buttons', max_length=1000)),
                ('files', models.ManyToManyField(to='generic.Attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreeField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('label', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('tree_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dtd.TreeData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('text', models.CharField(max_length=1000)),
                ('action_button', models.BooleanField(default=False)),
                ('is_header', models.BooleanField(default=False)),
                ('request', models.CharField(blank=True, max_length=1000)),
                ('categories', models.ManyToManyField(to='category.Category')),
                ('destination', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_link', to='dtd.TreeData')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dtd.TreeData')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketPriority')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreeOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('text', models.CharField(max_length=1000)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dtd.TreeField')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
