# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtd', '0002_auto_20160628_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treedata',
            name='key',
            field=models.CharField(max_length=254),
        ),
    ]
