# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtd', '0002_auto_20160226_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treedata',
            name='attachments',
        ),
    ]
