# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtd', '0004_auto_20160229_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treelink',
            name='parent',
        ),
        migrations.AddField(
            model_name='treelink',
            name='parents',
            field=models.ManyToManyField(related_name='links', to='dtd.TreeData'),
        ),
    ]
