# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtd', '0009_auto_20160302_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treedata',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='treedata',
            name='prompt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='treelink',
            name='request',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
