# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtd', '0012_auto_20160330_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treedata',
            options={'ordering': ('key',)},
        ),
        migrations.AlterField(
            model_name='treedata',
            name='key',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
