# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtd', '0013_auto_20160413_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treefield',
            name='type',
            field=models.CharField(choices=[('admin.dtd.label.field.text', 'admin.dtd.label.field.text'), ('admin.dtd.label.field.number', 'admin.dtd.label.field.number'), ('admin.dtd.label.field.textarea', 'admin.dtd.label.field.textarea'), ('admin.dtd.label.field.select', 'admin.dtd.label.field.select'), ('admin.dtd.label.field.checkbox', 'admin.dtd.label.field.checkbox'), ('admin.dtd.label.field.file', 'admin.dtd.label.field.file'), ('admin.dtd.label.field.asset_select', 'admin.dtd.label.field.asset_select'), ('admin.dtd.label.field.check_in', 'admin.dtd.label.field.check_in'), ('admin.dtd.label.field.check_out', 'admin.dtd.label.field.check_out')], default='admin.dtd.label.field.text', max_length=100),
        ),
    ]
