# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0005_auto_20160217_1642'),
        ('generic', '0006_delete_setting'),
        ('ticket', '0002_auto_20160217_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('key', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('field_label', models.CharField(max_length=1000)),
                ('field_type', models.CharField(blank=True, choices=[('text', 'text'), ('textarea', 'textarea'), ('select', 'select'), ('checkbox', 'checkbox'), ('file', 'file'), ('asset select', 'asset select'), ('check in', 'check in'), ('check out', 'check out')], default='text', max_length=1000)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('note_type', models.CharField(blank=True, choices=[('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='success', max_length=1000)),
                ('prompt', models.CharField(max_length=1000)),
                ('link_type', models.CharField(blank=True, choices=[('buttons', 'buttons'), ('links', 'links')], default='buttons', max_length=1000)),
                ('files', models.ManyToManyField(to='generic.Attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('text', models.CharField(max_length=100)),
                ('action_button', models.BooleanField(default=False)),
                ('is_header', models.BooleanField(default=False)),
                ('request', models.CharField(blank=True, max_length=1000)),
                ('categories', models.ManyToManyField(to='category.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreeOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('text', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='treelink',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decision_tree.TreeNode'),
        ),
        migrations.AddField(
            model_name='treelink',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketPriority'),
        ),
        migrations.AddField(
            model_name='treelink',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketStatus'),
        ),
        migrations.AddField(
            model_name='treedata',
            name='links',
            field=models.ManyToManyField(to='decision_tree.TreeLink'),
        ),
        migrations.AddField(
            model_name='treedata',
            name='options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decision_tree.TreeOption'),
        ),
    ]
