# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decision_tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treedata',
            name='links',
        ),
        migrations.RemoveField(
            model_name='treelink',
            name='destination',
        ),
        migrations.AddField(
            model_name='treelink',
            name='tree_data_links',
            field=models.ManyToManyField(related_name='tree_data_links', to='decision_tree.TreeData'),
        ),
        migrations.AddField(
            model_name='treelink',
            name='tree_data_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_data_parent', to='decision_tree.TreeData'),
        ),
        migrations.DeleteModel(
            name='TreeNode',
        ),
    ]
