# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decision_tree', '0003_remove_treedata_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treelink',
            name='destination',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='decision_tree.TreeData'),
        ),
    ]
