# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decision_tree', '0005_auto_20160229_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treelink',
            name='parents',
        ),
        migrations.AddField(
            model_name='treelink',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='decision_tree.TreeData'),
        ),
    ]
