# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_tree', '0007_auto_20160301_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treefield',
            name='type',
            field=models.CharField(choices=[('admin.dtd.field_type.text', 'admin.dtd.field_type.text'), ('admin.dtd.field_type.textarea', 'admin.dtd.field_type.textarea'), ('admin.dtd.field_type.select', 'admin.dtd.field_type.select'), ('admin.dtd.field_type.checkbox', 'admin.dtd.field_type.checkbox'), ('admin.dtd.field_type.file', 'admin.dtd.field_type.file'), ('admin.dtd.field_type.asset_select', 'admin.dtd.field_type.asset_select'), ('admin.dtd.field_type.check_in', 'admin.dtd.field_type.check_in'), ('admin.dtd.field_type.check_out', 'admin.dtd.field_type.check_out')], default='admin.dtd.field_type.text', max_length=100),
        ),
        migrations.AlterField(
            model_name='treelink',
            name='categories',
            field=models.ManyToManyField(related_name='links', to='category.Category'),
        ),
    ]
