# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_tree', '0010_auto_20160310_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='treefield',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
