# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 23:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import setting.mixins
import utils.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, help_text='If NULL the record is not deleted, otherwise this is the timestamp of when the record was deleted.', null=True)),
                ('title', models.CharField(help_text='i18n key used on front end. General settings uses this, others may as well.', max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('related_id', models.UUIDField(null=True)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
            ],
            bases=(utils.models.ToDictNameMixin, setting.mixins.SettingMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=set([('name', 'related_id')]),
        ),
    ]
