# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
