# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20160518_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='related_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=set([('name', 'related_id')]),
        ),
    ]
