# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20160519_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='title',
            field=models.CharField(help_text='i18n key used on front end. General settings uses this, others may as well.', max_length=100, null=True),
        ),
    ]
