# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 01:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(blank=True, max_length=254, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequestStatus',
            fields=[
                ('id', models.CharField(default='def11673-d4ab-41a6-a37f-0c6846b96006', editable=False, max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text="String value of the ID 'key'.", max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='workrequest',
            name='status',
            field=django_fsm.FSMKeyField(default='new', on_delete=django.db.models.deletion.CASCADE, protected=True, to='work_request.WorkRequestStatus'),
        ),
    ]
