# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 17:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('work_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=django_fsm.FSMKeyField(default='def11673-d4ab-41a6-a37f-0c6846b96006', on_delete=django.db.models.deletion.CASCADE, protected=True, to='work_request.WorkRequestStatus'),
        ),
    ]
