# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSetting',
        ),
        migrations.DeleteModel(
            name='MainSetting',
        ),
    ]
