# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
